main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('api/showtime/',views.ShowtimeList.as_view(), name='showtime'),
    path('api/showtime/create/', views.ShowtimeCreate.as_view(), name='create-showtime'),
    path('api/showtime/<int:pk>', views.ShowtimeDelete.as_view(), name='delete-show'),

    path('api/users/', views.UserDetail.as_view(), name ='user-info'),
    path('api/users/update/', views.UserUpdate.as_view(), name ='user-info-update'),
    path('api/users/delete/', views.UserDelete.as_view(), name ='user-delete'),

    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutPage, name='logout'),

    path('api/movies/', views.MovieList.as_view(), name='movies'),
    path('api/movies/<int:pk>/', views.MovieDetails.as_view(), name='movie-details'),
    path('api/movies/create/', views.MovieCreate.as_view(), name='create-movie'),
    path('api/movies/<int:pk>/update/',views.MovieUpdate.as_view(), name='update-movie'),
    path('api/movies/<int:pk>/delete/',views.MovieDelete.as_view(), name='delete-movie'),

    path('api/tickets/', views.TicketBooking.as_view(), name='book-a-ticket'),
    path('api/tickets/<int:pk>/', views.TicketCanceling.as_view(), name='cancel-ticket'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cosmo-cinema/', include('main.urls')),
]

main/models.py
from django.contrib.auth.models import User
from django.db import models

class MovieGenre(models.Model):
    genre_name = models.CharField(max_length=20)
    def __str__(self):
        return self.genre_name
    class Meta:

        db_table = 'MovieGenre'


class AgeRestrictions(models.Model):
    restriction = models.CharField(max_length=10)
    def __str__(self):
        return self.restriction
    class Meta:

        db_table = 'AgeRestrictions'


class AnimationFormat(models.Model):
    anima_format = models.CharField(max_length=2)
    def __str__(self):
        return self.anima_format
    class Meta:

        db_table = 'AnimationFormat'


class Movie(models.Model):
    title = models.CharField(max_length=50,null=False)
    mov_length = models.IntegerField()
    premiere = models.DateField()
    mvdescription = models.CharField(max_length=100)
    moviegenre = models.ForeignKey('MovieGenre', on_delete=models.CASCADE)
    agerestrictions = models.ForeignKey('AgeRestrictions', on_delete=models.CASCADE)
    animationformat = models.ForeignKey('AnimationFormat', on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    class Meta:

        db_table = 'Movie'


class Room(models.Model):
    room_number=models.IntegerField(null=False)
    seats_available=models.IntegerField(null=False)
    def __str__(self):
        return str(self.room_number)
    class Meta:

        db_table = 'Room'


class Showtime(models.Model):
    show_date=models.DateField()
    price=models.DecimalField(max_digits=4,decimal_places=2)
    movie=models.ForeignKey('Movie', on_delete=models.CASCADE)
    room=models.ForeignKey('Room', on_delete=models.CASCADE)
    startsAt=models.TimeField()
    endsAt=models.TimeField()
    def __str__(self):
        return f'{self.movie}     {self.show_date}'
    def getTimeline(self):
        return f'{self.startsAt} -- {self.endsAt}'
    class Meta:

        db_table = 'Showtime'



class Ticket(models.Model):
    showtime=models.ForeignKey('Showtime', on_delete=models.CASCADE)
    seat_num = models.IntegerField(null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tickets')
    def __str__(self):
        return f'Showtime: {self.showtime} | Viewer: {self.user} | Room: {self.showtime.room}   Seat: {self.seat_num}'
    class Meta:

        db_table = 'Ticket'

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Movie,Showtime,Ticket

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
            'first_name',
            'last_name',
        ]

class ShowtimeForm(forms.ModelForm):
    class Meta:
        model=Showtime
        fields = '__all__'

class TicketForm(forms.ModelForm):
    class Meta:
        model=Ticket
        fields = '__all__'


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie

        fields = '__all__'

main/views.py
from urllib.request import Request

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from rest_framework.decorators import permission_classes
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.renderers import TemplateHTMLRenderer

from rest_framework.views import APIView
from django.http import Http404
from rest_framework.response import Response
from .serializers import MovieSerializer,UserSerializer, TicketSerializer, ShowtimeSerializer
from rest_framework import status, generics, authentication, permissions

from .models import Ticket, Showtime, Movie
from .forms import RegistrationForm


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('main:showtime')

    form = AuthenticationForm(request, data=request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('main:showtime')
            else:
                form.add_error(None, "Invalid username or password")

    return render(request, 'main/login.html', {'form': form})
def registerPage(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            return redirect('main:showtime')
    else:
        form=RegistrationForm()
    return render(request, 'main/register.html', {'form': form})
@permission_classes([IsAuthenticated])
def logoutPage(request):
    logout(request)
    return redirect('main:showtime')


class UserDetail(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "main/viewer_info.html"

    def get_tickets(self,user):
        return Ticket.objects.filter(user=user)
    def get(self,request):
        if request.user.is_authenticated:
            user=get_object_or_404(User, username=request.user.username)
            tickets = self.get_tickets(user)
            serializer = UserSerializer(user)
            return Response({"serializer":serializer,
                             "user":user,
                             "tickets":tickets})
        else:
            return redirect('main:login')
class UserUpdate(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name ='main/update.html'

    def get(self, request):
        user = get_object_or_404(User, username=request.user.username)
        serializer = UserSerializer(user)
        return Response({"serializer": serializer, "user": user})
    def post(self, request):
        user = get_object_or_404(User, username=request.user.username)
        serializer = UserSerializer(user,data=request.data)
        if not serializer.is_valid():
            return Response({"serializer": serializer, "user": user})
        serializer.save()
        return redirect('main:user-info')
class UserDelete(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'main/delete.html'
    def get(self, request):
        user = get_object_or_404(User, username=request.user.username)
        serializer = UserSerializer(user)
        return Response({"serializer": serializer, "user": user})
    def post(self, request):
        user = get_object_or_404(User, username=request.user.username)
        logout(request)
        user.delete()
        return reverse_lazy('main:showtime')

class TicketBooking(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "main/create.html"
    def get(self, request):
        if request.user.is_authenticated:
            serializer = TicketSerializer()
            return Response({"serializer": serializer})
        else:
            return redirect('main:login')

    def post(self, request):
        if request.user.is_authenticated:
            serializer = TicketSerializer(data=request.data)
            if serializer.is_valid():
                serializer.save(user=request.user)
                return redirect('main:showtime')
            return redirect('main:showtime')
        else:
            return redirect('main:login')
class TicketCanceling(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'main/delete.html'
    def get(self, request, pk):
        ticket = get_object_or_404(Ticket, pk=pk)
        serializer = TicketSerializer(ticket)
        return Response({"serializer": serializer, "ticket": ticket})

    def post(self, request, pk):
        ticket = get_object_or_404(Ticket, pk=pk)
        ticket.delete()
        return redirect('main:user-info')

class ShowtimeUpdate(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "main/update.html"

    def get(self, request, pk):
        show = get_object_or_404(Showtime, pk=pk)
        serializer = MovieSerializer(show)
        return Response({"serializer": serializer, "show": show})
    def put(self, request, pk):
        if request.user.is_superuser:
            show = get_object_or_404(Movie, pk=pk)
            serializer = MovieSerializer(show, data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response({"serializer": serializer, "show": show})
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
class ShowtimeList(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name="main/showtime.html"

    def get (self,request, format=None):
        queryset=Showtime.objects.all()
        return Response({"showtime":queryset})
class ShowtimeCreate(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name="main/create.html"

    def get(self, request, format=None):
        serializer = ShowtimeSerializer()
        return Response({"serializer": serializer})
    def post(self,request, format=None):
        if request.user.is_superuser:
            serializer = ShowtimeSerializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return redirect('main:showtime')
            return Response({"serializer": serializer}, template_name="main/create.html")
class ShowtimeDelete(APIView):
    permission_classes = [IsAdminUser]
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'main/delete.html'
    def get(self, request, pk):
        show = get_object_or_404(Showtime, pk=pk)
        serializer = ShowtimeSerializer(show)
        return Response(serializer.data)

    def post(self, request, pk):
        show = get_object_or_404(Showtime, pk=pk)
        if request.user.is_superuser:
            show.delete()
            return redirect('main:showtime')
        return Response(status=status.HTTP_403_FORBIDDEN)


class MovieList(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'main/movies.html'

    def get(self, request):
        movies = Movie.objects.all()
        serializer = MovieSerializer(movies, many=True)
        return Response({'movies':serializer.data})
class MovieDetails(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "main/movie_details.html"

    def get(self,request, pk):
        movie=get_object_or_404(Movie, pk=pk)
        serializer = MovieSerializer(movie)
        return Response({"serializer":serializer,
                         "movie":movie})
class MovieCreate(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "main/create.html"
    def get(self, request, format=None):
        serializer = MovieSerializer()
        return Response({"serializer": serializer})
    def post(self, request):
        if request.user.is_superuser:
            serializer = MovieSerializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return redirect('main:showtime')
            return redirect('main:showtime')
class MovieUpdate(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name ='main/update.html'

    def get(self, request, pk):
        movie = get_object_or_404(Movie, pk=pk)
        serializer = MovieSerializer(movie)
        return Response({"serializer": serializer, "movie": movie})

    def post(self, request, pk):
        if request.user.is_superuser:
            movie = get_object_or_404(Movie, pk=pk)
            serializer = MovieSerializer(movie, data=request.data)
            if not serializer.is_valid():
                return Response({"serializer": serializer, "movie": movie})
            serializer.save()
            return redirect('main:showtime')
class MovieDelete(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'main/delete.html'
    def get(self, request, pk):
        movie = get_object_or_404(Movie, pk=pk)
        serializer = MovieSerializer(movie)
        return Response({"serializer": serializer, "movie": movie})

    def post(self, request, pk):
        if request.user.is_superuser:
            movie = get_object_or_404(Movie, pk=pk)
            movie.delete()
            return reverse_lazy('main:showtime')
        return Response(status=status.HTTP_403_FORBIDDEN)

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>CINEMA</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <meta charset="UTF-8">
</head>
<body>
{% include 'main/navigation_bar.html' %}

{% block content %}
{% endblock content %}

</body>
</html>

main/templates/main/create.html
{% extends 'main/base.html' %}

{% load rest_framework %}
<html><body>
{% block content %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        {% render_form serializer %}
        <input type="submit" value ="Create">
    </form>
</div>
{% endblock content %}
</body></html>

main/templates/main/delete.html
{% extends 'main/base.html' %}

{% load rest_framework %}
<html><body>
{% block content %}
<div>

<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure?</p>
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type="submit" value="Confirm"/>
</form>
</div>
{% endblock content %}
</body></html>

main/templates/main/login.html
{% extends 'main/base.html'%}

{% block content %}

<div>
    <h2>Login</h2>
    <form method="post", action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
    <p>Don`t have an account yet?</p>
    <h4><a href="{% url 'main:register' %}">Register</a></h4>
</div>
{% endblock content %}

main/templates/main/movie_details.html
{% extends 'main/base.html' %}

{% block content %}
<div>
    <h2>{{movie.title}}</h2>
    <p>Premier: {{movie.premiere}}</p>
    <p>Genre: {{movie.moviegenre}}</p>
    <p>Age restrictions: {{movie.agerestrictions}}</p>
    <p>Animation format: {{movie.animationformat}}</p>
    <p>Length: {{movie.mov_length}}</p>
    <p>Premiere: {{movie.premiere}}</p>
    <p>Description: {{movie.mvdescription}}</p>
</div>

{% if user.is_superuser %}
<h4><a href="{% url 'main:update-movie' movie.pk %}">Update movie information</a></h4>
<h4><a href="{% url 'main:delete-movie' movie.pk %}">Delete a movie</a></h4>
{% endif %}
{% endblock content %}

main/templates/main/movies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Showtime</title>
</head>
<body>
    <div>
        {% for movie in movies %}
        <div>
            <h2>{{movie.id}} -- <a href="{% url 'main:movie-details' movie.title %}"> {{movie.title}} </a></h2>
            <p>Date: {{movie.show_date}}</p>
            <p>Price: {{show.price}}</p>
            <p>Room: {{show.room}}</p>
            <p>Starts at: {{show.startsAt}}</p>
            <p>Ends at: {{show.endsAt}}</p>
            <hr>
        </div>
        {% endfor %}
    </div>
</body>
</html>

main/templates/main/navigation_bar.html
<h1 style="display:inline;"><span style="margin-left:0.7%;"><a href="{% url 'main:showtime' %}">SHOWTIME</a></span>
       <span style="margin-left:67%;"><a href="{% url 'main:user-info' %}">ACCOUNT</a></span>
</h1>
{% if user.is_authenticated %}
<h3><span style="margin-left:90%;"><a href="{% url 'main:logout' %}">Sign out</a></span></h3>
{% else %}
<h3><span style="margin-left:90%;"><a href="{% url 'main:login' %}">Sign in</a></span></h3>
{% endif %}

<hr>

main/templates/main/register.html
{% extends 'main/base.html'%}

{% block content %}
<div>
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
</div>

{% endblock content %}

main/templates/main/showtime.html
{% extends 'main/base.html' %}

{% block content %}
<div>
    {% for show in showtime %}
    <div>
        {% if show.movie%}
            <h2>{{show.id}} -- <a href="{% url 'main:movie-details' show.movie.pk %}"> {{show.movie}} </a></h2>
            <p>Date: {{show.show_date}}</p>
            <p>Price: {{show.price}}</p>
            <p>Room: {{show.room}}</p>
            <p>Starts at: {{show.startsAt}}</p>
            <p>Ends at: {{show.endsAt}}</p>
            <h4><a href="{% url 'main:book-a-ticket' %}">Book a ticket</a></h4>
            {% if user.is_asuperuser %}
                <h4><a href="{% url 'main:delete-show' show.id%}">Delete a show</a></h4>
            {% endif %}
        {% else %}
            <span>No movie available</span>
        {% endif %}
        <hr>
    </div>
    {% endfor %}
</div>
{% if user.is_superuser %}
<h2><a href = "{%url 'main:create-showtime'%}">Create a new show</a></h2>
<h2><a href = "{%url 'main:create-movie'%}">Add a new movie to showtime</a></h2>
{% endif %}
{% endblock content %}

main/templates/main/update.html
{% extends 'main/base.html' %}
{% load rest_framework %}
<html><body>
{% block content %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        {% render_form serializer %}
        <input type="submit" value="Save changes" />
    </form>
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
</div>
{% endblock content %}
</body></html>

main/templates/main/viewer_info.html
{% extends 'main/base.html' %}

{% block content %}
<div>
    <h2>Account information</h2>
    <div>
        <p>First name: {{user.first_name}}</p>
        <p>Last name: {{user.last_name}}</p>
        <p>Email: {{user.email}}</p>
        <h4><a href="{% url 'main:user-info-update' %}"> Update account information </a></h4>
        <h4><a href="{% url 'main:user-delete' %}"> Delete an account</a></h4>
    </div>
    <h2>Booked tickets</h2>
    <div>
        <div>
            {% for item in tickets %}
            <p>Movie: {{ item.showtime.movie.title }}</p>
            <p>Date: {{ item.showtime.show_date }}</p>
            <p>Cost: {{ item.showtime.price }}</p>
            <p>Room: {{ item.showtime.room.room_number }}</p>
            <p>Seat: {{ item.seat_num }}</p>
            <p>Runtime: {{ item.showtime.startsAt }} -- {{ item.showtime.endsAt }}</p>
            <hr>
            <h4><a href="{% url 'main:cancel-ticket' pk=item.id %}">Cancel booking</a></h4>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content%}